# vaasdev completion                                       -*- shell-script -*-

# This bash completions script was generated by
# completely (https://github.com/dannyben/completely)
# Modifying it manually is not recommended

_vaasdev_completions_filter() {
  local words="$1"
  local cur=${COMP_WORDS[COMP_CWORD]}
  local result=()

  if [[ "${cur:0:1}" == "-" ]]; then
    echo "$words"
  
  else
    for word in $words; do
      [[ "${word:0:1}" != "-" ]] && result+=("$word")
    done

    echo "${result[*]}"

  fi
}

_vaasdev_completions() {
  local cur=${COMP_WORDS[COMP_CWORD]}
  local compwords=("${COMP_WORDS[@]:1:$COMP_CWORD-1}")
  local compline="${compwords[*]}"

  case "$compline" in
    'config'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_vaasdev_completions_filter "check dump hook path prompt reset usage --help")" -- "$cur" )
      ;;

    'docker'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_vaasdev_completions_filter "setup start stop pid usage --help")" -- "$cur" )
      ;;

    'helm'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_vaasdev_completions_filter "setup --help")" -- "$cur" )
      ;;

    'aws'*)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_vaasdev_completions_filter "setup --help")" -- "$cur" )
      ;;

    *)
      while read -r; do COMPREPLY+=( "$REPLY" ); done < <( compgen -W "$(_vaasdev_completions_filter "config docker helm aws --help")" -- "$cur" )
      ;;

  esac
} &&
complete -F _vaasdev_completions vaasdev

# ex: filetype=sh
