#!/usr/bin/env sh

# vaas-docker-rootless-pid
#
# Helper script to return the pid of a rootless dockerd
# that was previously started with vaas-docker-rootless-start

if [ -f "$VAAS_HOME/dockerd.pid" ]; then
	cat "$VAAS_HOME/dockerd.pid" 2>/dev/null
fi

exit 0

