#!/usr/bin/env sh

# Start dockerd rootless, with all paths setup to isolate data within this
# directory as a standalone development environment.

ps -p $(vaas-docker-rootless-pid) >/dev/null 2>&1
if [[ $? -eq 0 ]]; then
	echo "ERROR: dockerd is already running; PID: $(vaas-docker-rootless-pid)"
	exit 1
fi

# Start dockerd-rootless
dockerd-rootless				\
	-p $VAAS_HOME/dockerd.pid	\
	-G $(id -g)					\
	> $VAAS_HOME/dockerd.log 2>&1 &
disown

# Wait until it is ready
while ! docker info >/dev/null 2>&1; do
	sleep 0.3
done

exit 0

