#!/usr/bin/env sh

# vaas-aws-setup
#
# Ensure that the awscli2 is configured and that the user has authenticated via
# the sso login, and can actively use it.
#
# This will open a browser to complete the authentication if needed.

eval $(vaas-configure hook)
if ! vaas-configure check ; then
	exit 1
fi

# Create the base configuration file
mkdir -p $VAAS_HOME/.aws
rm -f $VAAS_HOME/.aws/config
cat <<- EOF > $VAAS_HOME/.aws/config
	[default]
	output = json
	region = ${AWS_REGION}

	[profile trustnet-dev]
	sso_session = vaas
	sso_account_id = 497086895112
	sso_role_name = Vaas.Developer
	region = ${AWS_REGION}
	output = json

	[sso-session vaas]
	sso_start_url = https://d-926708eb5a.awsapps.com/start#/
	sso_region = ${AWS_REGION}
	sso_registration_scopes = sso:account:access
EOF

###########################################################
# Test AWS access; Login again if needed
###########################################################
aws sts get-caller-identity --profile ${AWS_PROFILE} --no-cli-pager >/dev/null 2>&1
if [[ $? -eq 0 ]]; then
	echo "Already logged into AWS"
else
	echo "Logging in to AWS..."
	aws sso login --profile ${AWS_PROFILE}

	if [[ $? -ne 0 ]]; then
		echo -en "ERROR: Failed to login to AWS.\n\n\n"
		. vaas-reset
		exit 1
	fi
fi

echo -en "Configuring k8s to use AWS... "
aws eks --region ${AWS_REGION} update-kubeconfig --name dev01 --role-arn arn:aws:iam::497086895112:role/eks/dev01-KubernetesDevelopers
if [[ $? -ne 0 ]]; then
	echo -en "ERROR: Failed to configure k8s to use aws.\n\n\n"
	exit 1
fi

echo -en "Setting default k8s context... "
kubectl config set-context --current --namespace=$DEVSTACK
if [[ $? -ne 0 ]]; then
	echo -en "ERROR: Failed to set the default k8s namespace to your devstack.\n\n\n"
	exit 1
fi

exit 0
